<<<<<<< HEAD
# Generated by Django 5.1 on 2025-11-28 01:54
=======
# Generated by Django 5.1 on 2025-11-28 03:50
>>>>>>> develop

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('bio', models.TextField(blank=True, max_length=500)),
=======
                ('bio', models.TextField(blank=True)),
>>>>>>> develop
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
<<<<<<< HEAD
            options={
                'ordering': ['-created_at'],
            },
=======
>>>>>>> develop
        ),
    ]
