# Generated by Django 5.1 on 2025-12-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
