from django.core.management.base import BaseCommand
from django.apps import apps
from django.conf import settings
import os

class Command(BaseCommand):
    help = 'Generate a Mermaid ER diagram (docs/db_schema_auto.mmd) from Django models'

    def add_arguments(self, parser):
        parser.add_argument('--apps', nargs='*', help='App labels to include (default: retros users)')

    def handle(self, *args, **options):
        app_labels = options.get('apps') or ['retros', 'users']

        lines = []
        lines.append('%% Auto-generated Mermaid ER diagram\n')
        lines.append('%% Generated by management command: generate_mermaid\n')
        lines.append('erDiagram\n')

        relations = []

        for app_label in app_labels:
            try:
                app_config = apps.get_app_config(app_label)
            except LookupError:
                self.stdout.write(self.style.WARNING(f"App '{app_label}' not found; skipping."))
                continue

            for model in app_config.get_models():
                model_name = model.__name__.upper()
                lines.append(f'    {model_name} {{\n')

                for field in model._meta.get_fields():
                    # skip reverse relations and autogenerated M2M through fields
                    if getattr(field, 'auto_created', False) and not getattr(field, 'concrete', False):
                        continue

                    # ForeignKey (many-to-one)
                    if getattr(field, 'many_to_one', False) and getattr(field, 'remote_field', None) is not None:
                        # use integer placeholder for FK
                        lines.append(f'        int {field.name}\n')
                        related = field.related_model.__name__.upper()
                        relations.append((related, model_name, field.name))
                        continue

                    # ManyToManyField (explicit)
                    if getattr(field, 'many_to_many', False) and getattr(field, 'concrete', False):
                        lines.append(f'        m2m {field.name}\n')
                        # Optionally could add relation lines for m2m
                        continue

                    # Normal/concrete fields
                    if getattr(field, 'concrete', False):
                        # attempt to get a readable type name
                        ftype = getattr(field, 'get_internal_type', None)
                        if callable(ftype):
                            ftype = field.get_internal_type()
                        else:
                            ftype = type(field).__name__
                        lines.append(f'        {ftype} {field.name}\n')

                lines.append('    }\n\n')

        # add unique relations in Mermaid format
        seen = set()
        for left, right, fname in relations:
            key = (left, right, fname)
            if key in seen:
                continue
            seen.add(key)
            # left (parent) ||--o{ right (child) : "field"
            lines.append(f'    {left} ||--o{{ {right} : "{fname}"\n')

        output_path = os.path.join(settings.BASE_DIR, 'docs', 'db_schema_auto.mmd')
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.writelines(lines)

        self.stdout.write(self.style.SUCCESS(f'Wrote {output_path}'))
