"""
Django settings for Purrgrammers backend project.

DJANGO SETTINGS EXPLAINED:
This file controls the entire Django application configuration:
- Database connections
- Security settings  
- Installed applications
- API configuration
- Static file handling
- Authentication setup

ENVIRONMENT-BASED CONFIGURATION:
- Development: uses .env file and local database
- Production: uses environment variables and Heroku Postgres
- Settings adapt automatically based on environment

SECURITY CONSIDERATIONS:
- Secret keys from environment variables (never commit to git)
- Debug mode controlled by environment
- CORS configured for specific frontend domains
- Allowed hosts configured for deployment

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# PYTHON IMPORTS:
from pathlib import Path  # Modern Python path handling
import os                 # Environment variable access
import dj_database_url    # Parse DATABASE_URL for Heroku deployment
from dotenv import load_dotenv  # Load .env file for local development

# ENVIRONMENT CONFIGURATION:
# load_dotenv() reads .env file and adds variables to os.environ
# This allows local development without setting system environment variables
# .env file should contain: DJANGO_SECRET_KEY, DATABASE_URL, etc.
# .env files should be in .gitignore (never commit secrets)
load_dotenv()

# PROJECT STRUCTURE:
# BASE_DIR points to project root directory (where manage.py lives)
# Path(__file__) = current file (settings.py)
# .resolve() = absolute path
# .parent.parent = go up two directories (settings.py -> backend_save_point -> project root)
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY CONFIGURATION:
# These settings control application security and should be carefully managed

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is used for:
# - Cryptographic signing (sessions, cookies, tokens)
# - Password reset tokens
# - CSRF protection
# - Security-sensitive operations
#
# ENVIRONMENT PATTERN:
# - Production: set DJANGO_SECRET_KEY environment variable
# - Development: fallback to default key (insecure, but convenient)
# - Never commit real secret keys to version control
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',  # Production: from environment variable
    'your_secret_key'  # Recommended that we do not hard code it in -- security issue
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG MODE EFFECTS:
# - Shows detailed error pages (security risk in production)
# - Enables Django Debug Toolbar
# - Collects static files differently
# - Changes logging behavior
#
# ENVIRONMENT LOGIC:
# - DEBUG=False if DJANGO_DEBUG environment variable equals 'False'
# - DEBUG=True for any other value or if not set (development default)
DEBUG = os.environ.get(
    'DJANGO_DEBUG'
) != 'False'

# ALLOWED_HOSTS: domains that can serve this Django app
# ['*'] allows all hosts (convenient for development, risky for production)
# Production should specify exact domains: ['yourdomain.com', 'api.yourdomain.com']
ALLOWED_HOSTS = ['*']

# CORS (Cross-Origin Resource Sharing) CONFIGURATION:
# Controls which domains can make API requests to this backend
# IMPORTANT: Frontend and backend are on different domains/ports

# CORS_ALLOWED_ORIGINS: specific domains allowed to make requests
CORS_ALLOWED_ORIGINS = [
    "https://save-point.netlify.app",  # Netlify domain
    "http://localhost:5173",           # For local development
]


# Application definition

INSTALLED_APPS = [
    'daphne', # websockets addon
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'retros.apps.RetrosConfig',
    'users.apps.UsersConfig',
    'teams.apps.TeamsConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

AUTH_USER_MODEL = 'users.CustomUser'

# added for EmailOrUsername login
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend', # fallback
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_save_point.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_save_point.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CHANNELS CONFIG
ASGI_APPLICATION = 'backend_save_point.asgi.application'

# Channel layers - Redis for production, in-memory for development
if os.environ.get('REDIS_URL'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [os.environ.get('REDIS_URL')],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }