# Generated by Django 5.1 on 2025-11-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
