# Generated by Django 5.1 on 2025-11-19 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0003_alter_vote_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'card'], name='retros_vote_user_card_idx'),
        ),
    ]
