# Generated by Django 5.1 on 2025-11-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0004_vote_retros_vote_user_card_idx'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroboard',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='retro_boards', to='teams.team'),
        ),
    ]
