# Generated by Django 5.1 on 2025-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0005_retroboard_assigned_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_type',
            field=models.CharField(choices=[('mad', 'Mad'), ('glad', 'Glad'), ('sad', 'Sad'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
