# Generated by Django 5.1 on 2025-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0006_alter_column_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_type',
            field=models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('continue', 'Continue'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
