# Generated by Django 5.1 on 2025-11-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0007_alter_column_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='retro_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_cards', to='retros.retroboard'),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='retros.column'),
        ),
    ]
