# Generated by Django 5.1 on 2025-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0008_card_retro_board_card_status_alter_card_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
