# Generated by Django 5.1 on 2025-11-30 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0009_alter_card_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['column', 'position'], name='retros_card_column__014b94_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['retro_board', 'status'], name='retros_card_retro_b_33d7c5_idx'),
        ),
    ]
