# Generated by Django 5.1 on 2025-12-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0011_actionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitem',
            name='original_column',
        ),
    ]
