# Generated by Django 5.1 on 2025-12-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0012_remove_actionitem_original_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('typescript', 'TypeScript'), ('django', 'Django'), ('nodejs', 'Node.js'), ('react', 'React'), ('angular', 'Angular'), ('tools', 'Tools'), ('team_culture', 'Team Culture'), ('workload', 'Workload'), ('communication', 'Communication'), ('custom', 'Custom')], max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='retros.tag'),
        ),
    ]
