# Generated by Django 5.1 on 2025-12-03 00:32

from django.db import migrations


def seed_tags(apps, schema_editor):
    """Populate the database with predefined tags"""
    Tag = apps.get_model('retros', 'Tag')
    
    tags = [
        # Languages
        'python',
        'javascript',
        'java',
        'csharp',
        'typescript',
        # Frameworks
        'django',
        'nodejs',
        'react',
        'angular',
        # Other
        'tools',
        'team_culture',
        'workload',
        'communication',
        'custom',
    ]
    
    for tag_name in tags:
        Tag.objects.get_or_create(name=tag_name)


def remove_tags(apps, schema_editor):
    """Reverse migration - remove seeded tags"""
    Tag = apps.get_model('retros', 'Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0013_tag_card_tags'),
    ]

    operations = [
        migrations.RunPython(seed_tags, remove_tags),
    ]
