# Generated by Django 5.1 on 2025-12-03 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0014_seed_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retro_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_rounds', to='retros.retroboard')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('retro_board', 'round_number')},
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='voting_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='retros.votinground'),
        ),
    ]
