# Generated by Django 5.1 on 2025-12-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0015_votinground_vote_voting_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retroboard',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
