# Generated by Django 5.1 on 2025-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0016_alter_column_title_alter_retroboard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroboard',
            name='max_votes_per_card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retroboard',
            name='max_votes_per_round',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
