# Generated by Django 5.1 on 2025-12-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0017_retroboard_max_votes_per_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('django', 'Django'), ('react', 'React'), ('git/github', 'Git/GitHub'), ('vscode', 'VSCode'), ('deployment', 'Deployment'), ('tools', 'Tools'), ('team_culture', 'Team Culture'), ('workload', 'Workload'), ('content', 'Content'), ('networking', 'Networking'), ('mentors', 'Mentors')], max_length=50, unique=True),
        ),
    ]
