# Generated by Django 5.1 on 2025-12-14 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0019_update_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retroboard',
            name='facilitators',
            field=models.ManyToManyField(blank=True, help_text='Users who can control voting and board settings', related_name='facilitated_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retroboard',
            name='participants_can_delete_any_card',
            field=models.BooleanField(default=False, help_text='Allow participants to delete cards created by others'),
        ),
        migrations.AddField(
            model_name='retroboard',
            name='participants_can_edit_board_title',
            field=models.BooleanField(default=False, help_text='Allow participants to change the board title'),
        ),
        migrations.AddField(
            model_name='retroboard',
            name='participants_can_edit_columns',
            field=models.BooleanField(default=True, help_text='Allow participants to create, edit, and delete columns'),
        ),
    ]
