# Generated by Django 5.1 on 2026-02-07 05:08

import uuid
from django.db import migrations, models


def generate_unique_invite_codes(apps, schema_editor):
    """Assign a unique UUID to each existing RetroBoard."""
    RetroBoard = apps.get_model('retros', 'RetroBoard')
    for board in RetroBoard.objects.all():
        board.invite_code = uuid.uuid4()
        board.save(update_fields=['invite_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('retros', '0021_populate_facilitators'),
    ]

    operations = [
        # Step 1: Add the field without unique constraint
        migrations.AddField(
            model_name='retroboard',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate existing rows with unique UUIDs
        migrations.RunPython(generate_unique_invite_codes, migrations.RunPython.noop),
        # Step 3: Now enforce unique constraint and remove null
        migrations.AlterField(
            model_name='retroboard',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
